version: '3'
services:

  #postgres DB container
    postgres:
        image: 'postgres:latest'
        environment:
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB=simple_blog_api
          - POSTGRES_USERNAME=postgres

  #Express server container
    api:
        build:
            dockerfile: Dockerfile.prod
            context: .
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_USERNAME=postgres
            - POSTGRES_DB=simple_blog_api
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_PORT=5432
        ports:
            - "3000:3000"
